site_name: Papers
site_url: https://orey.github.io/papers/
site_description: Olivier Rey's Papers
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2021 - Site licensed under the GNU FDL V3
google_analytics: ['UA-110156293-1', 'orey.github.io']
#repo_url: https://github.com/orey/papers/
#theme: readthedocs
site_dir: site
nav:
- Home:
    - 'Index': 'index.md'
    - 'Author': 'about/about.md'
    - 'License': 'about/LICENSE.md'
- Articles:
    - 'The Five Levels of Conceptual Maturity for IT Teams': 'articles/five-levels.md'
    - 'The V2 Vortex': 'articles/the-v2-vortex.md'
    - 'The Various Stages of Digital Transformation': 'articles/various-stages.md'
    - 'Considerations About Rest And Web Services': 'articles/about-rest.md'
    - 'GraphQL And Classic Web Services': 'articles/graphql-web-services.md'
    - 'A Simple Meta-Model for Portfolio Management': 'articles/portfolio.md'
    - 'An Introduction to The Archimate Revolution': 'articles/archimate-intro.md'
    - 'Archimate Recipes': 'articles/archimate-recipes.md'
    - 'Military frameworks, systems engineering and enterprise architecture': 'articles/mbse-vs-ea.md'
    - 'The real nature of data': 'articles/data-interop.md'
    - 'PLM and graph data': 'articles/about-plm.md'
- Graph-oriented programming:
    - 'First article on graph-oriented programming': 'graph/first-article.md'
    - 'Conference at the STAF/ICGT 2018 in Toulouse': 'graph/staf-icgt2018.md'
    - 'GraphApps project page': 'research/graphapps.md'
- Semantic Web:
    - 'Aerospace data migration': 'semantic/data-migration.md'
    - 'Semantic data migration project page': 'research/data-mig.md'
- Research:
    - 'Index': 'research/index-research.md'
    - 'Graph transformations': 'research/graph-transfo.md'
    - 'Basic graph transformations': 'research/basic-graph-transformations.md'
    - 'Basic semantic graph transformations': 'research/basic-semantic-graph-transformations.md'
    - 'DSL for graph topology check': 'research/DSL-for-graph-topology-checks.md'
    - 'Graph transformation applicability': 'research/graph-transformation-applicability.md'
    - 'Grammar of graph transformation': 'research/grammar-graph-transformation.md'
    - 'Graph-oriented programming language': 'research/graph-oriented-pl.md'
    - 'Reflections on industry data': 'research/industry-data.md'
    - 'UML to RDF considerations': 'research/rdf-design-patterns.md'
    - 'Towards a graph-oriented programming language?': 'research/graph-oriented-pl.md'
    - 'Resources': 'research/resources.md'
