site_name: Papers
site_url: https://orey.github.io/papers/
site_description: Olivier Rey's Papers
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2026 - Site licensed under the GNU FDL V3

theme:
    name: material

markdown_extensions:
#    - admonition
    - pymdownx.arithmatex:
#        inline_math_double: true
        generic: true
#    - pymdownx.superfences
#    - pymdownx.highlight
    - meta
    - toc:
        permalink: "#"
            #baselevel: 3
            #toc_depth: 3

extra_css:
    - stylesheets/styles.css

extra_javascript:
    - javascripts/config.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

google_analytics:
  - G-BZMZKWJP2V
  - auto
#google_analytics: ['UA-110156293-1', 'orey.github.io']
#repo_url: https://github.com/orey/papers/
#theme: readthedocs

site_dir: site

nav:
- BlogAI:
    - 'Blog index': 'blog/000-BlogIndex.md'
- PLM:
    - 'PLM and graph data': 'articles/about-plm.md'
    - 'Configuration management of industrial products in PDM/PLM': 'articles/conf-mgt.md'
    - 'The four core functions showing you need a PLM': 'articles/spreadsheet-and-PLM.md'
    - 'Semantic data migration in Industry': 'articles/data-mig.md'
    - 'Reflections on industry data': 'articles/industry-data.md'
- IT, Modeling & Data:
    - 'Digital Transformation Starts with the Change Agent Transformation': 'articles/change-agent.md'
    - 'What you should know about SAFe': 'articles/safe.md'
    - 'Legends of IT': 'articles/legends-of-it.md'
    - 'The real nature of data': 'articles/data-interop.md'
    - 'Military frameworks, systems engineering and enterprise architecture': 'articles/mbse-vs-ea.md'
    - 'A Simple Meta-Model for Portfolio Management': 'articles/portfolio.md'
    - 'An Introduction to The Archimate Revolution': 'articles/archimate-intro.md'
    - 'Archimate Recipes': 'articles/archimate-recipes.md'
#    - 'About artificial neural networks and machine learning': 'articles/about-ml.md'
    - 'Considerations About Rest And Web Services': 'articles/about-rest.md'
    - 'GraphQL And Classic Web Services': 'articles/graphql-web-services.md'
    - 'The Five Levels of Conceptual Maturity for IT Teams': 'articles/five-levels.md'
    - 'The V2 Vortex': 'articles/the-v2-vortex.md'
    - 'The Various Stages of Digital Transformation': 'articles/various-stages.md'
- About Graphs:
    - 'Graph-oriented programming': 'articles/first-article.md'
    - 'Conference at the STAF/ICGT 2018 in Toulouse': 'articles/staf-icgt2018.md'
    - 'GraphApps project page': 'articles/graphapps.md'
    - 'Towards a graph-oriented programming language?': 'articles/graph-oriented-pl.md'
    - 'Graph transformation index page': 'articles/index-research.md'
    - 'Graph transformations': 'articles/graph-transfo.md'
    - 'A general interoperability model using graph transformations': 'articles/graph-interop.md'
    - 'Basic graph transformations': 'articles/basic-graph-transformations.md'
    - 'Basic semantic graph transformations': 'articles/basic-semantic-graph-transformations.md'
    - 'DSL for graph topology check': 'articles/DSL-for-graph-topology-checks.md'
    - 'Graph transformation applicability': 'articles/graph-transformation-applicability.md'
    - 'Grammar of graph transformation': 'articles/grammar-graph-transformation.md'
    - 'UML to RDF considerations': 'articles/rdf-design-patterns.md'
- Various:
    - 'Paradoxe de Zénon et dépassement de la vitesse de la lumière': 'articles/zenon-lumiere.md'
    - 'A propos de la relativité générale': 'articles/relativite.md'
    - 'Einstein, Cartan et la géométrie différentielle': 'articles/cartan.md'
    - 'Resources': 'articles/resources.md'
- Conversations:
    - 'Conversation on quantum computing': 'conversations/20251115-Monday-QuantumComputing.md'
- About:
    - 'Author': 'about/about.md'
    - 'License': 'about/LICENSE.md'
