site_name: Papers
site_description: Olivier Rey's Papers
site_author: Olivier Rey
copyright: Copyright Olivier Rey 2017 - Site licensed under the GNU FDL V3
google_analytics: ['UA-110156293-1', 'orey.github.io']
repo_url: https://github.com/orey/papers/
#theme: readthedocs
site_dir: site
pages:
- Home: 'index.md'
- Articles:
    - 'The Five Levels of Conceptual Maturity for IT Teams': 'articles/five-levels.md'
    - 'The V2 Vortex': 'articles/the-v2-vortex.md'
    - 'The Various Stages of Digital Transformation': 'articles/various-stages.md'
    - 'Considerations About Rest And Web Services': 'articles/about-rest.md'
    - 'GraphQL And Classic Web Services': 'articles/graphql-web-services.md'
- About:
    - Author: 'about/about.md'
    - License: 'about/LICENSE.md'
